/**
 * AKSH Video & Audio Editor - Presets System
 * Standalone offline preset definitions for Visualizer and Anime Edit Quick Mode
 */

const Presets = (() => {
  const VisualizerPresets = {
    'neon-core': {
      id: 'neon-core',
      name: 'Neon Core',
      description: 'Dual high-energy cyan/magenta concentric rings with intense core glow and spark bursts',
      primaryColor: '#00f3ff',
      secondaryColor: '#ff0077',
      accentColor: '#ffffff',
      ringCount: 3,
      ringThickness: 4,
      ringRadius: 180,
      rotationSpeed: 1.0,
      sparkCount: 90,
      floatingCount: 40,
      shockwaveStrength: 1.2,
      cameraShake: 0.8,
      speedLines: 0.3,
      chromaticAberration: 0.5,
      glowIntensity: 1.5,
      vignette: 0.6,
      bgMotion: 'beat-zoom',
      particleSpeed: 1.2
    },
    'energy-ring': {
      id: 'energy-ring',
      name: 'Energy Ring',
      description: 'Segmented counter-rotating golden arcs with trailing stardust energy',
      primaryColor: '#ffb700',
      secondaryColor: '#ff5500',
      accentColor: '#fff4cc',
      ringCount: 4,
      ringThickness: 3.5,
      ringRadius: 200,
      rotationSpeed: 1.4,
      sparkCount: 75,
      floatingCount: 50,
      shockwaveStrength: 1.0,
      cameraShake: 0.6,
      speedLines: 0.2,
      chromaticAberration: 0.3,
      glowIntensity: 1.3,
      vignette: 0.65,
      bgMotion: 'ken-burns',
      particleSpeed: 1.0
    },
    'cyber-pulse': {
      id: 'cyber-pulse',
      name: 'Cyber Pulse',
      description: 'Futuristic cyberpunk neon green/cyan with digital scanlines and glitch flairs',
      primaryColor: '#00ff88',
      secondaryColor: '#00e1ff',
      accentColor: '#ffffff',
      ringCount: 2,
      ringThickness: 5,
      ringRadius: 190,
      rotationSpeed: 0.8,
      sparkCount: 110,
      floatingCount: 35,
      shockwaveStrength: 1.3,
      cameraShake: 0.7,
      speedLines: 0.4,
      chromaticAberration: 0.7,
      glowIntensity: 1.6,
      vignette: 0.7,
      bgMotion: 'subtle-motion',
      particleSpeed: 1.4
    },
    'anime-edit': {
      id: 'anime-edit',
      name: 'Anime Edit',
      description: 'Dark cinematic anime styling: deep crimson & violet, speed lines, dramatic camera shakes and heavy bass kicks',
      primaryColor: '#b026ff',
      secondaryColor: '#ff2a54',
      accentColor: '#ffffff',
      ringCount: 3,
      ringThickness: 4.5,
      ringRadius: 185,
      rotationSpeed: 1.2,
      sparkCount: 120,
      floatingCount: 60,
      shockwaveStrength: 1.6,
      cameraShake: 1.4,
      speedLines: 0.85,
      chromaticAberration: 0.9,
      glowIntensity: 1.8,
      vignette: 0.75,
      bgMotion: 'beat-shake',
      particleSpeed: 1.5
    },
    'aura': {
      id: 'aura',
      name: 'Aura',
      description: 'Smooth organic flame aura expanding and contracting with musical dynamics',
      primaryColor: '#7928ca',
      secondaryColor: '#ff0080',
      accentColor: '#ffeedd',
      ringCount: 5,
      ringThickness: 2,
      ringRadius: 170,
      rotationSpeed: 0.6,
      sparkCount: 50,
      floatingCount: 70,
      shockwaveStrength: 0.8,
      cameraShake: 0.4,
      speedLines: 0.1,
      chromaticAberration: 0.2,
      glowIntensity: 1.9,
      vignette: 0.55,
      bgMotion: 'slow-zoom-in',
      particleSpeed: 0.8
    },
    'spectrum': {
      id: 'spectrum',
      name: 'Spectrum',
      description: 'High-density radial circular equalizer radiating from behind the logo with outer particle spray',
      primaryColor: '#00f0ff',
      secondaryColor: '#7000ff',
      accentColor: '#ffffff',
      ringCount: 1,
      ringThickness: 3,
      ringRadius: 210,
      rotationSpeed: 0.5,
      sparkCount: 85,
      floatingCount: 45,
      shockwaveStrength: 1.1,
      cameraShake: 0.7,
      speedLines: 0.35,
      chromaticAberration: 0.4,
      glowIntensity: 1.4,
      vignette: 0.65,
      bgMotion: 'beat-zoom',
      particleSpeed: 1.1
    },
    'bass-shock': {
      id: 'bass-shock',
      name: 'Bass Shock',
      description: 'Maximum bass reactivity with explosive shockwaves and heavy bass punch zooms',
      primaryColor: '#ff1744',
      secondaryColor: '#ff9100',
      accentColor: '#ffffff',
      ringCount: 3,
      ringThickness: 6,
      ringRadius: 180,
      rotationSpeed: 1.6,
      sparkCount: 140,
      floatingCount: 50,
      shockwaveStrength: 2.0,
      cameraShake: 1.6,
      speedLines: 0.7,
      chromaticAberration: 1.0,
      glowIntensity: 2.0,
      vignette: 0.8,
      bgMotion: 'beat-zoom',
      particleSpeed: 1.8
    },
    'galaxy': {
      id: 'galaxy',
      name: 'Galaxy',
      description: 'Deep cosmic purple and starlight gold with swirling celestial orbital particles',
      primaryColor: '#8a2be2',
      secondaryColor: '#ffd700',
      accentColor: '#e6e6fa',
      ringCount: 4,
      ringThickness: 3,
      ringRadius: 195,
      rotationSpeed: 0.9,
      sparkCount: 80,
      floatingCount: 100,
      shockwaveStrength: 0.9,
      cameraShake: 0.5,
      speedLines: 0.25,
      chromaticAberration: 0.35,
      glowIntensity: 1.5,
      vignette: 0.7,
      bgMotion: 'ken-burns',
      particleSpeed: 0.9
    },
    'dark-cinematic': {
      id: 'dark-cinematic',
      name: 'Dark Cinematic',
      description: 'Atmospheric deep shadows, refined amber glow on drum transients, heavy film grain',
      primaryColor: '#e0a96d',
      secondaryColor: '#201e20',
      accentColor: '#ffffff',
      ringCount: 2,
      ringThickness: 3,
      ringRadius: 180,
      rotationSpeed: 0.7,
      sparkCount: 40,
      floatingCount: 45,
      shockwaveStrength: 0.7,
      cameraShake: 0.5,
      speedLines: 0.15,
      chromaticAberration: 0.3,
      glowIntensity: 1.2,
      vignette: 0.85,
      bgMotion: 'slow-zoom-out',
      particleSpeed: 0.7
    },
    'minimal-glow': {
      id: 'minimal-glow',
      name: 'Minimal Glow',
      description: 'Clean, sleek single neon ring with subtle bass pulse and crisp modern typography',
      primaryColor: '#ffffff',
      secondaryColor: '#00d2ff',
      accentColor: '#ffffff',
      ringCount: 1,
      ringThickness: 3,
      ringRadius: 175,
      rotationSpeed: 0.4,
      sparkCount: 25,
      floatingCount: 20,
      shockwaveStrength: 0.6,
      cameraShake: 0.2,
      speedLines: 0.0,
      chromaticAberration: 0.1,
      glowIntensity: 1.1,
      vignette: 0.5,
      bgMotion: 'subtle-motion',
      particleSpeed: 0.6
    }
  };

  /**
   * Anime Edit Quick Mode Intensity Multipliers
   */
  const AnimeEditIntensities = {
    'LOW': {
      label: 'Low',
      shockwaveStrength: 0.8,
      cameraShake: 0.5,
      speedLines: 0.3,
      chromaticAberration: 0.3,
      sparkCount: 50,
      bassSensitivity: 1.1,
      reactionStrength: 1.0,
      bgZoomSpeed: 0.0003
    },
    'MEDIUM': {
      label: 'Medium',
      shockwaveStrength: 1.3,
      cameraShake: 1.0,
      speedLines: 0.6,
      chromaticAberration: 0.6,
      sparkCount: 90,
      bassSensitivity: 1.4,
      reactionStrength: 1.3,
      bgZoomSpeed: 0.0006
    },
    'HIGH': {
      label: 'High',
      shockwaveStrength: 1.7,
      cameraShake: 1.5,
      speedLines: 0.9,
      chromaticAberration: 0.9,
      sparkCount: 130,
      bassSensitivity: 1.7,
      reactionStrength: 1.6,
      bgZoomSpeed: 0.001
    },
    'EXTREME': {
      label: 'Extreme',
      shockwaveStrength: 2.2,
      cameraShake: 2.0,
      speedLines: 1.2,
      chromaticAberration: 1.3,
      sparkCount: 180,
      bassSensitivity: 2.1,
      reactionStrength: 2.0,
      bgZoomSpeed: 0.0015
    }
  };

  return {
    VisualizerPresets,
    AnimeEditIntensities
  };
})();

if (typeof window !== 'undefined') {
  window.Presets = Presets;
}
